### ISSUE TITLE
Possible bug: Missing quickpanel for ref, include, etc.

### ISSUE THREAD

**Issue by diego898** [SublimeText/LaTeXTools#1055]
I just updated to 3.13.2, and I'm not exactly sure how but I no longer see the quick-panel when I type `\input, \cite, \ref, \cref`, etc.

**Comment by ig0774** [comment]
Odd... can you grab the output from the Sublime console (**View | Console**)?

**Comment by diego898** [comment]
This is a startup and compile:


```
startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/diego/Library/Application Support/Sublime Text 3/Packages
state path: /Users/diego/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/diego/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.439928
using gpu buffer for window
loading dictionary Packages/Language - English/en_US.dic
first paint time: 0.552801
startup time: 0.554114
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin Alignment.Alignment
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin FileDiffs.file_diffs
reloading plugin Filter Lines.filter
reloading plugin Filter Lines.fold
reloading plugin Gist.gist
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading plugin Google Spell Check.google-spell-check
reloading plugin LaTeXSmartQuotes.getTeXRoot
reloading plugin LaTeXSmartQuotes.smartquotes
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarTools.SideBar
reloading plugin SideBarTools.SideBarAPI
reloading plugin Wrap Plus.wrap_plus
reloading plugin LaTeXTools.01_reload_submodules
reloading plugin LaTeXTools.02_temp_file_cleanup
reloading plugin LaTeXTools.03_reset_phantoms
reloading plugin LaTeXTools.biblatex_crossref_completions
reloading plugin LaTeXTools.biblatex_field_name_completions
reloading plugin LaTeXTools.biblatex_name_completions
reloading plugin LaTeXTools.biblatex_snippet_completions
reloading plugin LaTeXTools.biblatex_syntax_listener
reloading plugin LaTeXTools.change_environment
reloading plugin LaTeXTools.create_mousemap
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.detect_spellcheck
reloading plugin LaTeXTools.getRegion
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpto_anywhere
reloading plugin LaTeXTools.jumpto_tex_file
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_cwl_completions
reloading plugin LaTeXTools.latex_directive_completions
reloading plugin LaTeXTools.latex_env_completions
reloading plugin LaTeXTools.latex_fill_all
reloading plugin LaTeXTools.latex_glossary_completions
reloading plugin LaTeXTools.latex_input_completions
reloading plugin LaTeXTools.latex_installed_packages
reloading plugin LaTeXTools.latex_own_command_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexDocumentationViewer
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.latextools_cache_listener
reloading plugin LaTeXTools.latextools_default_settings
reloading plugin LaTeXTools.latextools_plugin
reloading plugin LaTeXTools.latextools_sublime_version_listener
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.search_commands
reloading plugin LaTeXTools.system_check
reloading plugin LaTeXTools.texcount
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.texSyntaxListener
reloading plugin LaTeXTools.toc_quickpanel
reloading plugin LaTeXTools.toggle_auto
reloading plugin LaTeXTools.toggle_focus
reloading plugin LaTeXTools.toggle_fwdsync
reloading plugin LaTeXTools.toggle_show
reloading plugin LaTeXTools.toggle_view_on_build
reloading plugin LaTeXZeta.auto_complete
reloading plugin LaTeXZeta.auto_pair
reloading plugin LaTeXZeta.bracket_highligher
reloading plugin LaTeXZeta.generate_commands
reloading plugin LaTeXZeta.helpers
reloading plugin LaTeXZeta.latex_commands
reloading plugin LaTeXZeta.preview_math
reloading plugin PlainTasks.APlainTasksCommon
reloading plugin PlainTasks.PlainTasks
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
reloading plugin User.highlight-todo
plugins loaded
Loaded LaTeXTools plugins ['base_viewer'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers/base_viewer.py
Loaded LaTeXTools plugins ['skim_viewer', 'sumatra_viewer', 'okular_viewer', 'command_viewer', 'zathura_viewer', 'preview_viewer', 'evince_viewer'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers
Loaded LaTeXTools plugins ['traditional_bibliography', 'new_bibliography'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins
Loading LaTeXTools plugins...
Loaded LaTeXTools plugins ['pdf_builder'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/pdfBuilder.py
Loaded LaTeXTools plugins ['basic_builder', 'traditional_builder', 'simple_builder', 'script_builder'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders
Loaded LaTeXTools plugins [] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers/base_viewer.py
Loaded LaTeXTools plugins [] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers
Running "/usr/local/bin/gs -version"
Loaded LaTeXTools plugins [] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins
Package Control: Skipping automatic upgrade, last run at 2017-03-22 16:18:53, next run at 2017-03-22 17:18:53 or after
no command for selector: noop:
<class '_latextools_basicBuilder.BasicBuilder'>
8
Welcome to thread Thread-19
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
1
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
1
<class '_latextools_basicBuilder.BasicBuilder'>
8
Welcome to thread Thread-24
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
False True True
Jump to:  116 9
<class '_latextools_skim_viewer.SkimViewer'>
Running "/Applications/Skim.app/Contents/SharedSupport/displayline -r -g 117 '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/admm_journal.pdf' '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/distributed-push-forward.tex'"
<class '_latextools_basicBuilder.BasicBuilder'>
8
Welcome to thread Thread-30
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
False True True
Jump to:  114 36
<class '_latextools_skim_viewer.SkimViewer'>
Running "/Applications/Skim.app/Contents/SharedSupport/displayline -r -g 115 '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/admm_journal.pdf' '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/distributed-push-forward.tex'"
<class '_latextools_basicBuilder.BasicBuilder'>
8
Welcome to thread Thread-44
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
False True True
Jump to:  116 8
<class '_latextools_skim_viewer.SkimViewer'>
Running "/Applications/Skim.app/Contents/SharedSupport/displayline -r -g 117 '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/admm_journal.pdf' '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/distributed-push-forward.tex'"
<class '_latextools_basicBuilder.BasicBuilder'>
8
Welcome to thread Thread-108
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
1
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
1
<class '_latextools_basicBuilder.BasicBuilder'>
8
Welcome to thread Thread-123
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
False True True
Jump to:  117 66
<class '_latextools_skim_viewer.SkimViewer'>
Running "/Applications/Skim.app/Contents/SharedSupport/displayline -r -g 118 '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/admm_journal.pdf' '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/distributed-push-forward.tex'"
Jumpto tex file 'new_commands'
Open the file '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/new_commands.tex'
<class '_latextools_basicBuilder.BasicBuilder'>
19
Welcome to thread Thread-190
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
1
<class '_latextools_basicBuilder.BasicBuilder'>
12
Welcome to thread Thread-204
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
Running "bibtex admm_journal"
Finished normally
0
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
False True True
Jump to:  119 38
<class '_latextools_skim_viewer.SkimViewer'>
Running "/Applications/Skim.app/Contents/SharedSupport/displayline -r -g 120 '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/admm_journal.pdf' '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/distributed-push-forward.tex'"
<class '_latextools_basicBuilder.BasicBuilder'>
12
Welcome to thread Thread-226
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'admm_journal']
Running "pdflatex -interaction=nonstopmode -synctex=1 admm_journal"
Finished normally
0
False True True
Jump to:  119 38
<class '_latextools_skim_viewer.SkimViewer'>
Running "/Applications/Skim.app/Contents/SharedSupport/displayline -r -g 120 '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/admm_journal.pdf' '/Users/diego/Dropbox/My Research/Publications/ADMM Journal/distributed-push-forward.tex'"

```

I don't see any error, though `no command for selector: noop:` seems strange? Not sure its related to latextools

**Comment by diego898** [comment]
Even stanger - I'm **not** seeing the quickpanel when typing `\usepackage{temp1`, or '\ref,etc.` If I then type a comma `,` the quickpanel shows up!

**Comment by r-stein** [comment]
And when you press C-l, C-f?

**Comment by diego898** [comment]
The **first** time, I get a popup saying "No bib file found". If I then press ok, and try it again, the quick panel comes up. 

For `\ref`, the quick panel shows up

**Comment by diego898** [comment]
The **first** time, I get a popup saying "No bib file found". If I then press ok, and try it again, the quick panel comes up. 

For `\ref`, the quick panel shows up

**Comment by diego898** [comment]
The console for the `\cite` issue:

```
TEX root: '/Users/diego/Dropbox/My Research/Publications/journal paper/journal_paper.tex'
Bib files found: 
None
error: No bib files found!
TEX root: '/Users/diego/Dropbox/My Research/Publications/journal paper/journal_paper.tex'
Bib files found: 
('/Users/diego/Dropbox/My Research/Publications/journal paper/journal_paper_references.bib',)
```

**Comment by diego898** [comment]
Is this a bug anyone else is having?

**Comment by diego898** [comment]
@r-stein Do you know if this is also fixed by #1063 (essentially if this is the same as #1062) and so both can be closed?

**Comment by r-stein** [comment]
I don't neighter now here nor in #1062 what the problem behind the behavior realy is. My "this is already fixed" only targets a comment of the issue not the issue itself.

**Comment by diego898** [comment]
@r-stein a quick update of the latest behavior for `\cite` in a multiproject file. This is after a fresh restart

![](https://media.giphy.com/media/3og0IPQ86ypYWYOA8g/giphy.gif)

**Comment by r-stein** [comment]
Yes this also happens to me, but i can't always reproduce this. The cache sometimes seems to return None instead of throwing a `CacheMiss`.

**Comment by diego898** [comment]
It happens to me after every restart

**Comment by diego898** [comment]
Update - I now see this: 

```
startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/diego/Library/Application Support/Sublime Text 3/Packages
state path: /Users/diego/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/diego/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.472949
loading dictionary Packages/Language - English/en_US.dic
first paint time: 0.575188
startup time: 0.576622
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin Alignment.Alignment
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin FileDiffs.file_diffs
reloading plugin Filter Lines.filter
reloading plugin Filter Lines.fold
reloading plugin Gist.gist
reloading plugin Gist.helpers
reloading plugin Gist.request
reloading plugin Gist.settings
reloading plugin Google Spell Check.google-spell-check
reloading plugin LaTeXSmartQuotes.getTeXRoot
reloading plugin LaTeXSmartQuotes.smartquotes
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarTools.SideBar
reloading plugin Wrap Plus.wrap_plus
reloading plugin LaTeXTools.01_reload_submodules
reloading plugin LaTeXTools.02_temp_file_cleanup
reloading plugin LaTeXTools.03_reset_phantoms
reloading plugin LaTeXTools.biblatex_crossref_completions
reloading plugin LaTeXTools.biblatex_field_name_completions
reloading plugin LaTeXTools.biblatex_name_completions
reloading plugin LaTeXTools.biblatex_snippet_completions
reloading plugin LaTeXTools.biblatex_syntax_listener
reloading plugin LaTeXTools.change_environment
reloading plugin LaTeXTools.create_mousemap
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.detect_spellcheck
reloading plugin LaTeXTools.getRegion
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpto_anywhere
reloading plugin LaTeXTools.jumpto_tex_file
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_cwl_completions
reloading plugin LaTeXTools.latex_directive_completions
reloading plugin LaTeXTools.latex_env_completions
reloading plugin LaTeXTools.latex_fill_all
reloading plugin LaTeXTools.latex_glossary_completions
reloading plugin LaTeXTools.latex_input_completions
reloading plugin LaTeXTools.latex_installed_packages
reloading plugin LaTeXTools.latex_own_command_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexDocumentationViewer
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.latextools_cache_listener
reloading plugin LaTeXTools.latextools_default_settings
reloading plugin LaTeXTools.latextools_plugin
reloading plugin LaTeXTools.latextools_sublime_version_listener
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.search_commands
reloading plugin LaTeXTools.system_check
reloading plugin LaTeXTools.texcount
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.texSyntaxListener
reloading plugin LaTeXTools.toc_quickpanel
reloading plugin LaTeXTools.toggle_auto
reloading plugin LaTeXTools.toggle_focus
reloading plugin LaTeXTools.toggle_fwdsync
reloading plugin LaTeXTools.toggle_show
reloading plugin LaTeXTools.toggle_view_on_build
reloading plugin LaTeXYZ.auto_complete
reloading plugin LaTeXYZ.auto_pair
reloading plugin LaTeXYZ.bracket_highligher
reloading plugin LaTeXYZ.generate_commands
reloading plugin LaTeXYZ.helpers
reloading plugin LaTeXYZ.latex_commands
reloading plugin LaTeXYZ.preview_math
reloading plugin PlainTasks.APlainTasksCommon
reloading plugin PlainTasks.PlainTasks
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
reloading plugin User.highlight-todo
plugins loaded
Loading LaTeXTools plugins...
Loaded LaTeXTools plugins ['base_viewer'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers/base_viewer.py
Running "/usr/local/bin/gs -version"
Loaded LaTeXTools plugins ['preview_viewer', 'okular_viewer', 'zathura_viewer', 'command_viewer', 'skim_viewer', 'sumatra_viewer', 'evince_viewer'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers
Loaded LaTeXTools plugins ['pdf_builder'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/pdfBuilder.py
Loaded LaTeXTools plugins ['script_builder', 'basic_builder', 'traditional_builder', 'simple_builder'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders
Loaded LaTeXTools plugins ['traditional_bibliography', 'new_bibliography'] from path /Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins
Package Control: No updated packages
TEX root: '/Users/diego/Dropbox/My Research/Publications/journal paper/journal_paper.tex'
Bib files found: 
None
error: No bib files found!
TEX root: '/Users/diego/Dropbox/My Research/Publications/journal paper/journal_paper.tex'
Bib files found: 
<object object at 0x10c3860f0>
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_fill_all.py", line 1073, in run
    reraise(*sys.exc_info())
  File "/Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_fill_all.py", line 41, in reraise
    raise value
  File "/Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_fill_all.py", line 1067, in run
    view, prefix, line[::-1]
  File "/Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 472, in get_completions
    completions = get_cite_completions(view)
  File "/Users/diego/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 402, in get_cite_completions
    completions = run_plugin_command('get_entries', *bib_files)
TypeError: run_plugin_command() argument after * must be a sequence, not object

```

**Comment by r-stein** [comment]
@diego898 please see #1081 for that issue

**Comment by r-stein** [comment]
Can you please check whether this issue persists in the last update `v3.13.6`.

**Comment by diego898** [comment]
hey @r-stein I still get the error seen above, but now the `cite` pane doesnt show up at all - it used to sometimes show up.

**Comment by diego898** [comment]
Any idea why this might be caused or a potential work around? Its a bit annoying to not have the `cite` panel come up at all now.

**Comment by r-stein** [comment]
You coulduse an older version or may try this pr https://github.com/SublimeText/LaTeXTools/pull/1058 , which hopefully will fix most issues like the object thing https://github.com/SublimeText/LaTeXTools/pull/1058/commits/1479e7b8067a41afde40a9c1bc5ebace1711d849

**Comment by diego898** [comment]
I am not sure what happened, but the `\cite` panel is showing up after today's update. I will keep testing and report back!
