### ISSUE TITLE
Can't get rid of hourglass icons next to equations

### ISSUE THREAD

**Issue by quantumgolem** [SublimeText/LaTeXTools#1102]
So I installed LaTeXTools and decided to turn math live preview on in the settings. I don't have a LaTeX distribution currently installed on macOS, so it didn't work – hourglasses would pop up next to the equations and stay there perpetually. Now, I want to get rid of these hourglasses, but I can't. I set the math preview option to "none", I deleted my settings, and I even reinstalled LaTeXTools but those hourglasses just don't go away. Help please? They're killing m

**Comment by sn0wyfall** [comment]
What did I do to deserve this?

**Comment by r-stein** [comment]
If you set the preview option to none and close and open the file it should be away and shouldn't come back (even if there is an unhandled error. Can you open the console ``ctrl+` `` and look whether an error occurs?

**Comment by sn0wyfall** [comment]
Okay, so I made it none and reopened my tab. Here's what the console shows.

```
reloading settings Packages/User/LaTeXTools.sublime-settings
Running "pdflatex -interaction=nonstopmode d9398c40fd11050069b4a2d9470d058d.tex"
Traceback (most recent call last):
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/st_preview/preview_threading.py", line 117, in _start_threads
    func(job)
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/st_preview/preview_math.py", line 264, in _execute_job
    _create_image(**job)
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/st_preview/preview_math.py", line 135, in _create_image
    ], cwd=temp_path)
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 268, in execute_command
    show_window=show_window
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 221, in external_command
    cwd=cwd
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'pdflatex'
Running "pdflatex -interaction=nonstopmode 5f373bc5253d62b9b94e86a32b629edd.tex"
Traceback (most recent call last):
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/st_preview/preview_threading.py", line 117, in _start_threads
    func(job)
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/st_preview/preview_math.py", line 264, in _execute_job
    _create_image(**job)
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/st_preview/preview_math.py", line 135, in _create_image
    ], cwd=temp_path)
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 268, in execute_command
    show_window=show_window
  File "/Users/sn0wyfall/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 221, in external_command
    cwd=cwd
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'pdflatex'
```

**Comment by r-stein** [comment]
To make it clear you have `"preview_math_mode": "none",` in your settings and no `"preview_math_mode":` setting below of that? Also does the compilation succeed?

**Comment by sn0wyfall** [comment]
> To make it clear you have `"preview_math_mode": "none"`, in your settings and no `"preview_math_mode":` setting below of that?

Yep, I can confirm that `"preview_math_mode":` only appears once in `...Sublime Text 3/Packages/User/LaTeXTools.sublime-settings`. 

> Also does the compilation succeed?

I'm not sure what you mean here exactly. I'm not compiling the TeX document myself as I don't have a LaTeX distribution installed. As for the hourglasses, they remain hourglasses. They don't do anything or show anything. The console doesn't show anything, either -- it just stops after the file not found error.

**Comment by r-stein** [comment]
> I'm not sure what you mean here exactly. I'm not compiling the TeX document myself as I don't have a LaTeX distribution installed. As for the hourglasses, they remain hourglasses. They don't do anything or show anything. The console doesn't show anything, either -- it just stops after the file not found error.

We kinda expect a tex distribution to be installed and didn't handle the error well. I will improve that.

Unfortunately I can't reproduce the issue, that the hour glas doesn't go away. You may also have it in the project/view settings (which have precedence). However you can try to edit [this line](https://github.com/SublimeText/LaTeXTools/blob/v3.13.6/st_preview/preview_math.py#L33), set `_IS_ENABLED = False`, and restart ST afterwards.

**Comment by sn0wyfall** [comment]
> Unfortunately I can't reproduce the issue, that the hour glas doesn't go away.

Do you have a TeX distribution installed? I think most likely it's because I don't, so it tries to compile but can never succeed. That might be the issue, but I'm just guessing.

> However you can try to edit this line, set _IS_ENABLED = False, and restart ST afterwards.

I did that, and they went away! At long last. Thank you :).

I was actually wondering something... instead of using a TeX distribution, can the rendering engine use [MathJax](https://www.mathjax.org) instead? In that case it is much faster and also doesn't need a TeX distribution installed. I think this is how the MarkdownPreviewPlus works on Atom, which can show a live preview of math equations, without lag and without my having to have a TeX distribution installed. What do you think about that?

**Comment by r-stein** [comment]
>> Unfortunately I can't reproduce the issue, that the hour glass doesn't go away.
>
> Do you have a TeX distribution installed? I think most likely it's because I don't, so it tries to compile but can never succeed. That might be the issue, but I'm just guessing.

I tried to simulate the error by changing the source code to raise it, but wasn't able to reproduce the behavior, that it did not disappear after changing the setting.

> I was actually wondering something... instead of using a TeX distribution, can the rendering engine use [MathJax](https://www.mathjax.org) instead? In that case it is much faster and also doesn't need a TeX distribution installed. I think this is how the MarkdownPreviewPlus works on Atom, which can show a live preview of math equations, without lag and without my having to have a TeX distribution installed. What do you think about that?

MathJax is a JavaScript library, which can be integrated into browsers. Since Atom packages are written in JavaScript/Coffeescript and Atom itself is based on a browser, it is a natural choice there.  However Sublime Text is not browser based and the packages are written in python, hence we can't just use it the way Atom does. (We would require a JavaScript interpreter like node or rhino and it would not be as fast as in Atom.) In addition AFAIK MathJax doesn't commands like `\usepackage`, such that it would be less powerful.
Futhermore I assume people to have TeX distribution installed if they use LaTeXTools, so I am not looking forward in removing that as a dependency for certain features (it should not produce bugs if you have none). I still don't really understand how you would write LaTeX in a productive way without having a TeX distribution to compile it.

**Comment by sn0wyfall** [comment]
> MathJax is a JavaScript library, which can be integrated into browsers.

Ah, I see. That makes sense, yes. Thanks a lot for the explanation. 

> I still don't really understand how you would write LaTeX in a productive way without having a TeX distribution to compile it.

Hahaha! Don't worry, right now I use Overleaf to compile some of my code when I need to. I haven't installed a distribution yet because I don't have much space.

I'm actually a bit busy at the moment. After I'm free in a week or so I'll do some testing and try to exactly reproduce this issue, and get back to you about it.
