### ISSUE TITLE
Math preview won't display

### ISSUE THREAD

**Issue by RadicalOlly** [SublimeText/LaTeXTools#1109]
LaTeXTools just updated to 3.14.0 and the maths preview won't show anything in any of the scopes I'm looking in (inline, equation, equation*, align, align*, etc). I thought it might be one of the settings entered incorrectly but copying the string in the comment and pasting it into the user options doesn't fix it. I opened the console and this is the display when I click in a maths scope and this is the traceback. 

Traceback (most recent call last):
  File "C:\Users\Olly\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 558, in on_after_selection_modified_async
    self.update_phantoms()
  File "C:\Users\Olly\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 618, in update_phantoms
    self._update_phantoms()
  File "C:\Users\Olly\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 655, in _update_phantoms
    math_scopes = view.find_by_selector(self.math_scope)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 882, in find_by_selector
    return sublime_api.view_find_by_selector(self.view_id, selector)
TypeError: String required

**Comment by r-stein** [comment]
You may need to restart Sublime Text

**Comment by RadicalOlly** [comment]
And of course, that was the only thing I didn't try.

Thanks anyway

**Comment by filipjurukovic** [comment]
In my case, only the inline math preview doesn't work. There are no errors at the console when selecting an inline math environment, it just does nothing. Tried `"preview_math_mode": "all"` to no avail. Tried restarting ST3.

**Comment by RadicalOlly** [comment]
Add this to your latextools user settings

`"preview_math_scope": "text.tex.latex meta.environment.math",`

**Comment by noosoon** [comment]
Thank you! I was looking for something like this, but was searching in my User Settings file.
