### ISSUE TITLE
after (auto)-upgrading to 3.14, autocomplete of citekeys doesn't work

### ISSUE THREAD

**Issue by rcorty** [SublimeText/LaTeXTools#1110]

**Comment by r-stein** [comment]
Have you tried to restart Sublime Text?

**Comment by rcorty** [comment]
Yes.  So far, my process has been:

LaTeXTools autoupgraded when I turned on ST2.  I started working on my document. I quickly noticed I wasn't getting autocomplete after typing "\citep{".

I restarted ST2.   No autocomplete after "\citep{".

I used package control to remove and add LaTeXTools back.  No autocomplete after "\citep{".

I removed LaTeXTools using package control.  I downloaded version 3.13 from github, moved it to the sublime text packages directory, and renamed it "LaTeXTools" (deleting version information from the directory name, which seemed to cause a problem).  No autocomplete after "\citep{".

**Comment by r-stein** [comment]
Please try to run `LaTeXTools: Clear Document Cache` and `LaTeXTools: Clear current bibliography cache` from the command panel ``C-shift-p``. If that does not help open the console ``ctrl+` `` and check for error messages.

**Comment by rcorty** [comment]
@r-stein, I followed your instructions and then restarted ST2 and now it works again.  Thanks!

**Comment by jdumas** [comment]
I got the same problem, and the console show the following error message:

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/home/jdumas/.config/sublime-text-3/Packages/LaTeXTools/latex_fill_all.py", line 1073, in run
    reraise(*sys.exc_info())
  File "/home/jdumas/.config/sublime-text-3/Packages/LaTeXTools/latex_fill_all.py", line 41, in reraise
    raise value
  File "/home/jdumas/.config/sublime-text-3/Packages/LaTeXTools/latex_fill_all.py", line 1067, in run
    view, prefix, line[::-1]
  File "/home/jdumas/.config/sublime-text-3/Packages/LaTeXTools/latex_cite_completions.py", line 474, in get_completions
    completions = get_cite_completions(view)
  File "/home/jdumas/.config/sublime-text-3/Packages/LaTeXTools/latex_cite_completions.py", line 404, in get_cite_completions
    completions = run_plugin_command('get_entries', *bib_files)
TypeError: run_plugin_command() argument after * must be a sequence, not object
```

I tried to clear document + bibliography cache and restart sublime, to no avail.

**Comment by r-stein** [comment]
@jdumas You can try to open the cache folder `import os; os.startfile(sublime.cache_path() + "/LaTeXTools")` and delete the `local_cache` folder and the bib caches. Afterwards restart ST. That object error is a bug we are working on.

**Comment by jdumas** [comment]
Seems to be working good now. Thanks!
