### ISSUE TITLE
\cite autocompletion not working anymore

### ISSUE THREAD

**Issue by musm** [SublimeText/LaTeXTools#1115]
```
2017-05-16 15:01:56,839: 14060: DEBUG: on_selection_modified
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_fill_all.py", line 1073, in run
    reraise(*sys.exc_info())
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_fill_all.py", line 41, in reraise
    raise value
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_fill_all.py", line 1067, in run
    view, prefix, line[::-1]
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 474, in get_completions
    completions = get_cite_completions(view)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 404, in get_cite_completions
    completions = run_plugin_command('get_entries', *bib_files)
TypeError: run_plugin_command() argument after * must be a sequence, not object
2017-05-16 15:01:56,842: 14060: DEBUG: on_post_text_command
2017-05-16 15:01:56,945: 14060: DEBUG: on_idle
2017-05-16 15:02:04,851: 14060: DEBUG: on_hover
2017-05-16 15:02:05,901: 14060: DEBUG: on_hover
```

`\ref` works but for some reason `\cite` no longer works?

**Comment by r-stein** [comment]
Can you delete your bibcache? (C-shift-p "LaTeXTools: Clear bibliography cache) We are aware of this problem and working on it #1081

**Comment by musm** [comment]
```
['C:\\Users\\Mus\\Dropbox (MIT)\\publications\\phd_thesis\\working_copy\\main.bib']
2017-05-16 15:17:04,336: 14972: DEBUG: on_modified
2017-05-16 15:17:04,337: 14972: DEBUG: post_on_modified
2017-05-16 15:17:04,339: 14972: DEBUG: on_selection_modified
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_fill_all.py", line 1073, in run
    reraise(*sys.exc_info())
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_fill_all.py", line 41, in reraise
    raise value
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_fill_all.py", line 1067, in run
    view, prefix, line[::-1]
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 474, in get_completions
    completions = get_cite_completions(view)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 404, in get_cite_completions
    completions = run_plugin_command('get_entries', *bib_files)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 367, in run_plugin_command
    result = _run_command(plugins)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cite_completions.py", line 334, in _run_command
    result = getattr(plugin, command)(*args, **kwargs)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins\newBibliography.py", line 140, in get_entries
    bib_data = parser.parse(bibf.read())
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\external\bibtex\parser.py", line 57, in parse
    self.tokens = self.lexer.tokenize(s)
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\external\bibtex\lexer.py", line 88, in tokenize
    self.token_error()
  File "C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\external\bibtex\lexer.py", line 302, in token_error
    self.code[self.current_index:].split('\n', 1)[0]
SyntaxError: 4789:10 - unrecognised token ":/content/aapt/journal/ajp/70/7/10.1119/1.1477428,"
2017-05-16 15:17:04,355: 14972: DEBUG: on_post_text_command
2017-05-16 15:17:04,448: 14972: DEBUG: on_idle
command: drag_select {"event": {"button": 1, "x": 799.5, "y": 1299.5}}

```

no luck :(

**Comment by musm** [comment]
anything else I could try?

**Comment by r-stein** [comment]
It looks like you are using the "newBibliography" you can try to switch to traditional in the [settings](https://github.com/SublimeText/LaTeXTools/blob/v3.14.0/LaTeXTools.sublime-settings#L553). That is more tolerant.

**Comment by musm** [comment]
omg yes it works!!

**Comment by musm** [comment]
BTW why do I get `?????` below
![untitled](https://cloud.githubusercontent.com/assets/4319522/26124482/95f69370-3a4c-11e7-9306-9eb35195fd19.png)


corresponding entry
![image](https://cloud.githubusercontent.com/assets/4319522/26124498/a75b2748-3a4c-11e7-98c2-b418fea87131.png)

**Comment by r-stein** [comment]
I don't know that should work, can you please insert the entry as plain text inside  block quotes (```)

**Comment by musm** [comment]
Not exactly sure what you mean?

**Comment by r-stein** [comment]
Please paste text examples as plain text and not as images, so we can just copy them to reproduce the error. You can put the text into [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/), such that it keeps its formatting.

**Comment by musm** [comment]
Yes of course sorry about that. Well all my bib files are UTF-8  because I user Biber. Now it looks like using 'traditional' does not correctly parse elements of the strings in the autocomplete box

**Comment by musm** [comment]
Oh wait I figured it out

`  date         = {1958-02}, `

**Comment by ig0774** [comment]
@musm: Can you possible post the bib entry that has `:/content/aapt/journal/ajp/70/7/10.1119/1.1477428,` in it?

**Comment by musm** [comment]
```
@article{:/content/aapt/journal/ajp/70/7/10.1119/1.1477428,
   author = "Berthet, R. and Petrosyan, A. and Roman, B.",
   title = "An analog experiment of the parametric instability",
   journal = "American Journal of Physics",
   year = "2002",
   volume = "70",
   number = "7", 
   pages = "744-749",
   url = "http://scitation.aip.org/content/aapt/journal/ajp/70/7/10.1119/1.1477428",
   doi = "http://dx.doi.org/10.1119/1.1477428" 
}
```

**Comment by ig0774** [comment]
Ok... I get why that failed. I didn't realise you could use such things as bibliography keys. I'll have a go at fixing the parser.

**Comment by lrdegeest** [comment]
Same problem on my end. `\ref{}` works but not `\cite{}` or natbib variants (e.g. `\citep{}`). Same trace back message: `TypeError: run_plugin_command() argument after * must be a sequence, not object`
