### ISSUE TITLE
no such context scope:source.c++#unique-keywords

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1140]
I just upgraded to Sublime Text build 3132, and start noticed this popping when Sublime Text starts:
```
no such context scope:source.c++#unique-keywords at line 182 column 16 in Packages/LaTeX/LaTeX.sublime-syntax
no such context scope:source.c++#unique-numbers at line 199 column 16 in Packages/LaTeX/LaTeX.sublime-syntax
no such context scope:source.c++#unique-strings at line 195 column 16 in Packages/LaTeX/LaTeX.sublime-syntax
no such context scope:source.c++#unique-variables at line 170 column 16 in Packages/LaTeX/LaTeX.sublime-syntax
no such context scope:source.c++#unique-constants at line 177 column 16 in Packages/LaTeX/LaTeX.sublime-syntax
```

Full start log: [LatexToolsSublimeStartLog.txt](https://gist.github.com/evandrocoan/a9255467534783f266f827cfcc3267cd)

There is also this other log error which is started a little after the Sublime Start: (also captured on the log above)
```
Traceback (most recent call last):
  File "D:\SublimeText\Data\Packages\LaTeXTools\latextools_utils\cache.py", line 326, in cache
    return self.get(key)
  File "D:\SublimeText\Data\Packages\LaTeXTools\latextools_utils\cache.py", line 562, in get
    raise CacheMiss(unicode(e))
LaTeXTools.latextools_utils.cache.CacheMiss: cannot load created timestamp

During handling of the above exception, another exception occurred:
```

**Comment by r-stein** [comment]
Not sure about the C++ thing have you changed the C syntax or something like that?

The other exception is expected and handled, but the `another exception occurred:` would be the interesting part.

**Comment by evandrocoan** [comment]
I noticed this error:
```
no such context scope:source.c++#unique-keywords at line 182 column 16 in Packages/LaTeX/LaTeX.sublime-syntax
no such context scope:source.c++#unique-numbers at line 199 column 16 in Packages/LaTeX/LaTeX.sublime-syntax
```
Do not happens every time Sublime Text start, only some times I think. Because I looked now on the console and it was not there.

I think I do not override the C the syntax. This is the report [Override Report.txt](https://gist.github.com/evandrocoan/8f13c6e0abc79de0a0a46c606711b4b0) I just did with the package 
[OverrideAudit](https://github.com/OdatNurd/OverrideAudit), it not point to the C syntax. Also these are my [installed settings](https://github.com/evandrocoan/SublimeTextStudio), including all overriding/replacements, if want to check.
