### ISSUE TITLE
'LatexFillAllCommand' object has no attribute 'window'

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1159]
I just opened the console and I saw this:
```latex
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 720, in is_visible_
    ret = self.is_visible()
  File "D:\SublimeText\Data\Packages\LaTeXTools\latex_fill_all.py", line 880, in is_visible
    view = self.window.active_view()
AttributeError: 'LatexFillAllCommand' object has no attribute 'window'
```
The code on the line ``880` was added today on this commit  https://github.com/SublimeText/LaTeXTools/commit/7cc70ff603db3cd9d3ea46b93f6c7639b79e886f

**Comment by r-stein** [comment]
Thanks I just copied it from a WindowCommand to a TextCommand
