### ISSUE TITLE
Glossaries autocomplete does not work

### ISSUE THREAD

**Issue by Mq89** [SublimeText/LaTeXTools#1168]
I am running LaTeXTools v3.14.0 (2017-05-10) in Sublime Text 2 build 2221.

I am using the acronym feature from the glossaries package.
Whenever I want to use an acronym I type "\gls" when I hit the opening curly bracket "{" the autocompletion fails with the following error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./latex_fill_all.py", line 1085, in run
TypeError: object of type 'object' has no len()
```

The bracket is not inserted into the document and no autocompletion appears. Manually typing the command and compiling the document works fine.
Feel free to ask me for further details.

**Comment by Mq-** [comment]
Reinstalling LaTeXTools solved the issue.

**Comment by r-stein** [comment]
If that happens again you can try to execute the "LaTeXTools: Clear Cache" command.
