### ISSUE TITLE
Toggle menu for \cite not working

### ISSUE THREAD

**Issue by jultes** [SublimeText/LaTeXTools#1178]
I have ST3 and it has been working fine up until now. All of a sudden I cannot access the drop down menu anymore, when typing \cite{, but instead it will simply paste the name of a random item of my bib entries. I have neither changed my bib file nor the tex project. I tried to clear the cache, but nothing changed, still pasting the same bibtex entry as soon as I press { after the cite command. From the console feedback, I am also sure it finds my bib-file itself, but something else must have happened...

Does anyone know how to fix this? Any help is greatly appreciated.
Thanks!

```
TEX root: '/path/main.tex'
Bib files found: 
['/path/BibTeXFile_1.bib']
Loaded 1 bibitems
Found 1 total bib entries
Running "'' -version"
Error finding Ghostscript version for None
Traceback (most recent call last):
  File "/path/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/st_preview/preview_utils.py", line 99, in _update_gs_version
    raw_version = check_output([_GS_COMMAND, '-version'])
  File "/Users/julita/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 348, in check_output
    show_window=show_window
  File "/Users/julita/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 268, in execute_command
    show_window=show_window
  File "/Users/julita/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 221, in external_command
    cwd=cwd
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1370, in _execute_child
  File "./python3.3/os.py", line 791, in fsencode
TypeError: expect bytes or str, not NoneType
```

**Comment by r-stein** [comment]
The error in the console is not related to the behavior. Yuo may try to clear your cache and try it again.
