### ISSUE TITLE
Referencing in multiple file environment

### ISSUE THREAD

**Issue by josepas** [SublimeText/LaTeXTools#1197]
Hello I am having a problem with label tags that are inside caption tags. As advised [here](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing)

When a label is declared within a float environment, the \ref{...} will return the respective fig/table number, but it must occur after the caption. When declared outside, it will give the section number. To be completely safe, the label for any picture or table can go within the \caption{} command, as in

`\caption{Close-up of a gull \label{fig:gull} }`

And probably inside any other par of {}. 

Also the references are not being updated when I save the file. I have to close and open sublime again for them to be updated.

This is what I get on the sublime console:

```
Error finding Ghostscript version for None
Traceback (most recent call last):

  File "C:\Users\praktikant\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_utils.py", line 99, in _update_gs_version
    raw_version = check_output([_GS_COMMAND, '-version'])
  File "C:\Users\praktikant\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 348, in check_output
    show_window=show_window
  File "C:\Users\praktikant\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 268, in execute_command
    show_window=show_window
  File "C:\Users\praktikant\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 181, in external_command
    if not os.path.isabs(command[0]):
  File "./python3.3/ntpath.py", line 102, in isabs
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

**Comment by r-stein** [comment]
- Nested commands are only supported in the [prereleases](https://github.com/SublimeText/LaTeXTools#prereleases), so just enable them to get that working or just write it behind the caption
- The error output is because it does not find ghostscript to create the equation preview #785, but it should be more silent about that
