### ISSUE TITLE
Check System no longer working

### ISSUE THREAD

**Issue by RaphaelArkadyMeyer** [SublimeText/LaTeXTools#1209]
When I run check system via the command palate, I see no output, and find the following exception in the sublime log:

Exception in thread Thread-56:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\Raphael A. Meyer\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\system_check.py", line 571, in run
    run_on_main_thread(partial(self._on_main_thread, results), timeout=30)
  File "C:\Users\Raphael A. Meyer\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\utils.py", line 161, in run_on_main_thread
    return func()
  File "C:\Users\Raphael A. Meyer\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\system_check.py", line 661, in _on_main_thread
    options.extend(tex_directives.get('options', []))
AttributeError: 'str' object has no attribute 'extend'

I somewhat recently upgraded machines, and recall this working when I install LaTeXTools less then 3 months ago.

**Comment by ig0774** [comment]
Just quickly, it looks like your `options` setting is set to a string instead of a list, i.e., something like `"--shell-escape"` rather than `["--shell-escape"]`. This'll be fixed in the next version, but if you want it to work now, just change to the second format.
