### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1235]
After changing the rulers on my project settings I got this on my console:
```
Traceback (most recent call last):
  File "D:\SublimeText\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 415, in update_preamble_str
    self.preamble_str = "\n".join(self.preamble)
TypeError: can only join an iterable
reloading /D/User.sublime-project
```

The lines mentioned are:
```python
File: LaTeXTools/st_preview/preview_math.py
411:         def update_preamble_str(init=False):
412:             if isinstance(self.preamble, str):
413:                 self.preamble_str = self.preamble
414:             else:
415:                 self.preamble_str = "\n".join(self.preamble)
416: 
417:             if not init:
418:                 self.reset_phantoms()
```

___

Related:

1. https://github.com/Monnoroch/ColorHighlighter/issues/370 AttributeError: 'bool' object has no attribute 'find'

**Comment by evandrocoan** [comment]
Now I after restarting Sublime Text I got the error on another line:
```python
File:  LaTeXTools/st_preview/preview_math.py
404:     def _init_watch_settings(self):
405:         # listen to setting changes to update the phantoms
406:         def update_packages_str(init=False):
407:             print( "self.packages: " + str( self.packages ) )
408:             self.packages_str = "\n".join(self.packages)
409:             if not init:
410:                 self.reset_phantoms()
```
But this time I added `print( "self.packages: " + str( self.packages ) )` before it, and this was the result:
```
self.packages: 0
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 408, in update_packages_str
    self.packages_str = "\n".join(self.packages)
TypeError: can only join an iterable
```

**Comment by r-stein** [comment]
What is the content of your [preview_math_template_preamble](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.2/LaTeXTools.sublime-settings#L143) setting (and the packages for the other issue)?

**Comment by evandrocoan** [comment]
It is:
```javascript
	"preview_math_template_preamble": "",
```
 But what is his packages settings? Is this:
```javascript
	"preview_math_template_packages": [
		"\\usepackage{amsmath}",
		"\\usepackage{amssymb}",
		"\\IfFileExists{latexsym.sty}{\\usepackage{latexsym}}{}",
		"\\IfFileExists{mathtools.sty}{\\usepackage{mathtools}}{}"
	],
```

**Comment by evandrocoan** [comment]
Now after the fix, it is doing the error on another line:
```
self.preamble:                      None
hasattr(self.preamble, "__iter__"): False
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 611, in reset_phantoms
    self.update_phantoms()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 623, in update_phantoms
    self._update_phantoms()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 660, in _update_phantoms
    math_scopes = view.find_by_selector(self.math_scope)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime.py", line 882, in find_by_selector
    return sublime_api.view_find_by_selector(self.view_id, selector)
TypeError: String required
```
The:
```
self.preamble:                      None
hasattr(self.preamble, "__iter__"): False
```
Is the print I added:
```
File: LaTeXTools/st_preview/preview_math.py
413:         def update_preamble_str(init=False):
414:             if isinstance(self.preamble, str):
415:                 self.preamble_str = self.preamble
416:             else:
417:                 print( "self.preamble:                      " + str( self.preamble ) )
418:                 print( "hasattr(self.preamble, \"__iter__\"): " + str( hasattr(self.preamble, "__iter__") ) )
419:                 self.preamble_str = "\n".join(self.preamble) if hasattr(self.preamble, "__iter__") else ""
420: 
421:             if not init:
422:                 self.reset_phantoms()
```

But the other lines are:
```
File: LaTeXTools\st_preview\preview_math.py
648:         # update the regions of the phantoms
649:         self._update_phantom_regions()
650: 
651:         new_phantoms = []
652:         job_args = []
653:         if not _IS_ENABLED or self.visible_mode == "none":
654:             if not self.phantoms:
655:                 return
656:             scopes = []
657:         elif self.visible_mode == "all":
658:             scopes = view.find_by_selector(self.math_scope)
659:         elif self.visible_mode == "selected":
660:             math_scopes = view.find_by_selector(self.math_scope)
661:             scopes = [scope for scope in math_scopes
662:                       if any(scope.contains(sel) for sel in view.sel())]
663:         else:
664:             self.visible_mode = "none"
665:             scopes = []
```

**Comment by evandrocoan** [comment]
After also putting a print there, I saw `self.math_scope: 0`, and I committed on the pull request a check for 0 before trying to use the value.

**Comment by deathaxe** [comment]
Fixed by 4.1
