### ISSUE TITLE
No bib files found using autocomplete \citet

### ISSUE THREAD

**Issue by thomas-noe** [SublimeText/LaTeXTools#1410]
Hello: I am using Mac OS 10.12.4. My problem is that although when I compile (using the traditional build) bibtex produces bibliography entries, when I type \citet{ or \citep{ in hopes that the list of bib entries will appear, instead I receive the message "No bib files found. "
The bib file is in the same directory as tex file. 
I tried clearing the bibliography cache, renaming the file with a lower case name, running pdflatex bibtex pdflatex pdflatex, and other recommended cures on the web. No luck.

The only possible source of this problem I can identify is that, when I opened the console and tried to run LateXTools: Clear Cache the following message appeared

Error while trying to delete global cache
Traceback (most recent call last):
  File "/Users/thomaenoe/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/delete_temp_files.py", line 32, in run
    shutil.rmtree(cache._global_cache_path())
  File "./python3.3/shutil.py", line 478, in rmtree
  File "./python3.3/shutil.py", line 360, in _rmtree_unsafe
  File "./python3.3/shutil.py", line 358, in _rmtree_unsafe
FileNotFoundError: [Errno 2] No such file or directory: '/Users/thomaenoe/Library/Application Support/Sublime Text 3/Cache/LaTeXTools/internal'
Error while trying to delete local cache
Traceback (most recent call last):
  File "/Users/thomaenoe/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/delete_temp_files.py", line 32, in run
    shutil.rmtree(cache._global_cache_path())
  File "./python3.3/shutil.py", line 478, in rmtree
  File "./python3.3/shutil.py", line 360, in _rmtree_unsafe
  File "./python3.3/shutil.py", line 358, in _rmtree_unsafe
FileNotFoundError: [Errno 2] No such file or directory: '/Users/thomaenoe/Library/Application Support/Sublime Text 3/Cache/LaTeXTools/internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thomaenoe/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/delete_temp_files.py", line 37, in run
    shutil.rmtree(cache._local_cache_path())
AttributeError: 'module' object has no attribute '_local_cache_path'

However, no error message appears when I execute Latex Tools: Clear current bibliography cache.
Any help on this issue, which I find very puzzling, would be much appreciated. The problem is new. I have not previously had any problems with this very useful feature of Latex Tools.
Regards

**Comment by ig0774** [comment]
How are you loading the bib file in your document? Are you using `\bibliography`, `\addbibresource` or something else?
