### ISSUE TITLE
LatexTools not working on windows

### ISSUE THREAD

**Issue by brupelo** [SublimeText/LaTeXTools#1470]
Hello, newbie user here and trying to get started but I'm having some issues. Here's the steps I've followed:

- Installed/updated latest miktex & sumatra versions and made sure they were available in %PATH% 
- Launched ST3 & installed LatexTools
- Check System Check log

```
Variable   Value
--------   -----
PATH       ...other paths...;d:\software\miktex\miktex29\miktex\bin\x64\
TEXINPUTS  None 
BIBINPUTS  None 
BSTINPUTS  None 

Program      Location  Status   Version
-------      --------  ------   -------
sublime                missing  unavailable
texify                 missing  unavailable
pdflatex               missing  unavailable
xelatex                missing  unavailable
lualatex               missing  unavailable
biber                  missing  unavailable
bibtex                 missing  unavailable
bibtex8                missing  unavailable
kpsewhich              missing  unavailable
magick                 missing  unavailable
ghostscript            missing  unavailable

Packages for equation preview  Status
-----------------------------  ------
standalone                     missing
preview                        missing
xcolor                         missing
amsmath                        missing
amssymb                        missing
latexsym                       missing
mathtools                      missing

Builder      Status
-------      ------
traditional  available

Builder Setting  Value
---------------  -----
display_log      False
linux            {}   
osx              {}   
windows          {}   

Viewer   Status     Location
------   ------     --------
sumatra  available  d:\software\miktex\miktex29\miktex\bin\x64\SumatraPDF.exe
```

- After that report I've checked manually the paths in some terminal and I've realized many of them would be available though, ie:

```
$ where sublime                                                            
INFO: Could not find files for the given pattern(s).                          
$ where sublime_text                                                       
D:\sources\personal\sublimetext3\sublime_text.exe                          
$ where texify                                                             
d:\software\miktex\miktex29\miktex\bin\x64\texify.exe                         
$ where pdflatex                                                           
d:\software\miktex\miktex29\miktex\bin\x64\pdflatex.exe                    
$ where xelatex                                                            
d:\software\miktex\miktex29\miktex\bin\x64\xelatex.exe                        
$ where lualatex                                                           
d:\software\miktex\miktex29\miktex\bin\x64\lualatex.exe                    
$ where biber                                                              
d:\software\miktex\miktex29\miktex\bin\x64\biber.exe                       
$ where bibtex                                                             
d:\software\miktex\miktex29\miktex\bin\x64\bibtex.exe                      
$ where bibtex8                                                            
d:\software\miktex\miktex29\miktex\bin\x64\bibtex8.exe                     
$ where kpsewhich                                                          
d:\software\miktex\miktex29\miktex\bin\x64\kpsewhich.exe                   
$ where magick                                                             
INFO: Could not find files for the given pattern(s).                       
$ where ghostscript                                                        
INFO: Could not find files for the given pattern(s).                       
$ where standalone                                                         
INFO: Could not find files for the given pattern(s).                       
$ where preview                                                            
INFO: Could not find files for the given pattern(s).                       
$ where xcolor                                                             
INFO: Could not find files for the given pattern(s).                       
$ where amsmath                                                            
INFO: Could not find files for the given pattern(s).                       
$ where amssymb                                                            
INFO: Could not find files for the given pattern(s).                       
$ where latexsym                                                           
INFO: Could not find files for the given pattern(s).                       
$ where mathtools                                                          
INFO: Could not find files for the given pattern(s).                       
```

- `Reset User Settings to Default` 
- Set texpath to either `"texpath" : "$PATH",` or `"texpath" : "",`

Unfortunately that didn't work and if I try to compile a simple tex such as:

```
\documentclass[a4paper]{article}
\begin{document}
Hello xxx!werwer
\end{document}
```

Using `LaTex` build system I'll get:

```
TraditionalBuilder: Engine: pdflatex. Invoking texify... 

COULD NOT COMPILE!

Attempted command:d:\software\miktex\miktex29\miktex\bin\x64\texify.EXE -b -p --engine=pdftex --tex-option="--synctex=1" texto-1.tex
Build engine: Traditional Builder
```

With the console error:

```
>>> 
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
8
Welcome to thread Thread-344
Running "'d:\software\miktex\miktex29\miktex\bin\x64\texify.EXE' -b -p --engine=pdftex '--tex-option="--synctex=1"' texto-1.tex"
Traceback (most recent call last):
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\makePDF.py", line 317, in run
    cwd=self.caller.tex_dir
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\latextools_utils\external_command.py", line 221, in external_command
    cwd=cwd
  File "./python3.3/subprocess.py", line 784, in __init__
  File "./python3.3/subprocess.py", line 980, in _get_handles
  File "./python3.3/subprocess.py", line 1030, in _make_inheritable
OSError: [WinError 6] The handle is invalid

```

I've read on the internet everybody saying wonderful things about this package and I'd love to give it a shot but so far the initial experience has been really painful :crying_cat_face:  ... So, could you please advice? Is this a bug or it's just me being clumsy?

**Comment by r-stein** [comment]
Have you tried to restart sublime text or your PC? Obviously this should not happen, but it is hard to see what's the problem from the error message.

**Comment by brupelo** [comment]
About restarting sublime text, yeah, definitely (few times while debuggin)... in fact, i've uninstalled/installed the package (removed completely all the remaining settings) as well.

Also, few hours ago I've opened this [https://forum.sublimetext.com/t/lightweight-workflow-to-edit-preview-latex-docs-in-st3/50149/7](https://forum.sublimetext.com/t/lightweight-workflow-to-edit-preview-latex-docs-in-st3/50149/7)... in there you'll find some additional info related to this one... I've stoped debugging as I didn't know the cause of the traceback i was seeing (you can see the traceback in that thread).

That said, gonna restart the PC... that's something I didn't do yet :) . Tbh, I'd love to give it a shot to this package so I can stop using TexStudio et al

**Comment by ig0774** [comment]
The other suggestion would be to try the basic builder (ctrl + shift + b should let you change the builder). TeXify is the default builder when using MiKTeX on Windows, but that’s largely for historical reasons. TeXify doesn’t tend to provide helpful output (there’s a logging file somewhere; I don’t remember where exactly, but it seems like you might be running into some other issue). 

If that doesn’t work, try running the command you see in the output in a CMD or Powershell window. That may give a better clue as to what is going on.

**Comment by brupelo** [comment]
Here's what I've tried, I've removed the package, as well as caches, .bak, and all possible references to `LatexTools`... said otherwise, ST3 almost clean. I've restarted the PC. Miktex&Ghostscript in path and i've installed this package back. Show console and this is what showed:

```
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 369, in <lambda>
    lambda: check_view_event_listeners(view))
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 359, in check_view_event_listeners
    listeners.append(cls(view))
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 395, in __init__
    self._init_watch_settings()
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 488, in _init_watch_settings
    update_packages_str(init=True)
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 407, in update_packages_str
    self.packages_str = "\n".join(self.packages)
TypeError: can only join an iterable
generating meta info summary
Loading LaTeXTools plugins...
Traceback (most recent call last):
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 380, in check_all_view_event_listeners
    check_view_event_listeners(v)
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 359, in check_view_event_listeners
    listeners.append(cls(view))
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 395, in __init__
    self._init_watch_settings()
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 488, in _init_watch_settings
    update_packages_str(init=True)
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 407, in update_packages_str
    self.packages_str = "\n".join(self.packages)
TypeError: can only join an iterable
reloading /D/sources/personal/sublimetext3/Data/Packages/User/Package Control.sublime-settings
Loaded LaTeXTools plugins ['base_viewer'] from path D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\viewers\base_viewer.py
Loaded LaTeXTools plugins ['preview_viewer', 'zathura_viewer', 'sumatra_viewer', 'evince_viewer', 'okular_viewer', 'command_viewer', 'skim_viewer'] from path D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\viewers
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Loaded LaTeXTools plugins ['traditional_bibliography', 'new_bibliography'] from path D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\bibliography_plugins
Loaded LaTeXTools plugins [] from path D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\builders\pdfBuilder.py
Loaded LaTeXTools plugins [] from path D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\builders
Traceback (most recent call last):
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 369, in <lambda>
    lambda: check_view_event_listeners(view))
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 359, in check_view_event_listeners
    listeners.append(cls(view))
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 395, in __init__
    self._init_watch_settings()
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 488, in _init_watch_settings
    update_packages_str(init=True)
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 407, in update_packages_str
    self.packages_str = "\n".join(self.packages)
TypeError: can only join an iterable
Traceback (most recent call last):
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 380, in check_all_view_event_listeners
    check_view_event_listeners(v)
  File "D:\sources\personal\sublimetext3\sublime_plugin.py", line 359, in check_view_event_listeners
    listeners.append(cls(view))
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 395, in __init__
    self._init_watch_settings()
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 488, in _init_watch_settings
    update_packages_str(init=True)
  File "D:\sources\personal\sublimetext3\Data\Packages\LaTeXTools\st_preview\preview_math.py", line 407, in update_packages_str
    self.packages_str = "\n".join(self.packages)
TypeError: can only join an iterable

```

I can try again with a fresh ST3 version but it looks to me like the version living in `package control repos` is just broken :/

**Comment by brupelo** [comment]
After a lot of researching I've figured out how to reproduce this bug quite easily.

Make sure to spawn sublime_text from the terminal, that way the package will be broken completely. Why? Because the current version it's assuming SublimeText is always spawned "normally" (ie: as a explorer.exe subprocess child on windows instead cmd's one)... Ideally the package should run normally no matter how sublime text has been spawned though.

Finally I'm testing the package and it's pretty awesome actually... Offtopic, when I'm not working on a latex document, the package won't be consuming any resources in the background, right?

**Comment by r-stein** [comment]
Thanks for reproducing this. If you have no latex document open should not consume additional resources. However currently every start time from sublime text is delayed a little bit until it is fully loaded, because this a rather big package and we have some mechanism during the package loading. We are planing to move to a lazy load mechanism, but it does not yet exists.

**Comment by deathaxe** [comment]
Can't reproduce in v4. All working well, regardless ST being started via shell or explorer.
