### ISSUE TITLE
error into DDExecute.py during load of plugin

### ISSUE THREAD

**Issue by reyman** [SublimeText/LaTeXTools#160]
I have problem with latextools plugin loading into ST2 :

I use the package tools to enable sublime.

reloading plugin /home/srey/.config/sublime-text-2/Packages/LaTeXTools/DDEExecute.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./DDEExecute.py", line 2, in <module>
    from ctypes import *
  File ".\ctypes\__init__.py", line 10, in <module>
ImportError: No module named _ctypes

**Comment by ig0774** [comment]
I'm closing this as we no longer have any of the DDE code in the plugin.
