### ISSUE TITLE
Errors after parsing log file

### ISSUE THREAD

**Issue by ghost** [SublimeText/LaTeXTools#28]
I'm afraid I'm not particularly knowledgeable in this area, so I can't be more specific. A friend recommended that I use Sublime Text 2 for LaTeX, and I wound up using this extension. It works fine for all of my various math assignments that I have been working on, but the plugin stalls when I try to compile a lab report I've been working on. The report is perfectly fine, and compiles fine in TeXWorks - I'm using MiKTeX. I would imagine there might be some trouble with the rather complicated ACS styles (it's not the first time they've given me troubles), but this error isn't very telling. I pasted the console output below and have uploaded the complete log to:

{link removed}

... (sliced to remove unnecessary things). See comment below for further details.
[u'texify', u'-b', u'-p', u'--tex-option="--synctex=1"', u'C:\Users\Jacob\Documents\College\CHM 343 (Lab)\Lab 5\_report.tex']
Welcome to thread Thread-3
2
Finished normally
0
Parsing log file
Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\makePDF.py", line 299, in run
  File ".\makePDF.py", line 218, in parseTeXlog
  File ".\makePDF.py", line 57, in handle_warning
IndexError: list index out of range

**Comment by themmes** [comment]
Still warns me about the log, does compile. 
Absolute path apparently does the trick as the warning disappears.
