### ISSUE TITLE
\Cite Autocompletion Crashes (Latin Enc Issue)

### ISSUE THREAD

**Issue by rbuehl** [SublimeText/LaTeXTools#281]
Autocompletion crashes on Line 59 (latex_cite_completions.py), using Latin-1 encoded tex-files on my OSX 10.9, ST2. 

Console Output is:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./latex_cite_completions.py", line 422, in run
  File "./latex_cite_completions.py", line 190, in get_cite_completions
  File "./latex_cite_completions.py", line 94, in find_bib_files
  File "./latex_cite_completions.py", line 59, in find_bib_files
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/codecs.py", line 671, in read
    return self.reader.read(size)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 593: invalid start byte 

Issue seems to be a change in line 49/50 with https://github.com/SublimeText/LaTeXTools/commit/41fee02c9625d2e01abd1cb9ab18cbfa2c8fd670. Going back to "src_file = open(file_path, "r")" fixed the problem for me. 

Same applies to latex_ref_completions.py, https://github.com/SublimeText/LaTeXTools/commit/9a6a3a1674e8eec89be476e7cc8ea6a944afbfcf.

**Comment by deathaxe** [comment]
In 2025 utf-8 is the way to go.
