### ISSUE TITLE
bibtex entries without a citekey

### ISSUE THREAD

**Issue by RoyalTS** [SublimeText/LaTeXTools#365]
I've got a gigantic BibTeX file that Mendeley creates for me and since I'm a lazy organizer some of the entries in the BibTeX file don't have a citekey. An example:

```
@article{,
title = {{Eliciting Beliefs : Proper Scoring Rules , Incentives , Stakes and Hedging}},
year = {2010}
}
```

Unfortunately, this seems to trip up the cite completion, which throws the following error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./latex_cite_completions.py", line 417, in run
  File "./latex_cite_completions.py", line 287, in get_cite_completions
TypeError: cannot concatenate 'str' and 'dict' objects`
```

This, I think, should be an easy fix. Just replace line 287 with

```
print ("Previous record: " + str(entry))
```

You could also make the error message a tad more informative by replacing the iterator on line 255 by

```
for idx,line in enumerate(bib):
```

and changing line 286 to something like

```
print ("Cannot process the @ line on line " + str(idx+1) + " in " + bibfname)
```

(sorry I'm not sending you this as a pull request but I don't have access to a full development environment at the moment)

**Comment by deathaxe** [comment]
The cite key is what entries are organized and uniquely referenced by. It must be present.
