### ISSUE TITLE
Build does not generate .log file, .pdf creation fails

### ISSUE THREAD

**Issue by susanemcg** [SublimeText/LaTeXTools#398]
Not sure if this is similar to #358 but when I build a simple .tex file, I get the following:

```
TraditionalBuilder: Invoking latexmk... done.
```

However, Skim does not launch and the .pdf isn't generated. Checking the Sublime console I see:

```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "./makePDF.py", line 147, in run
IOError: [Errno 2] No such file or directory: u'/Users/suZe/Desktop/Publishing/attempt.log'
```

When I run latex or pdflatex from the command line, all works as expected (and a .log file is generated), so I think my general setup is ok. Any suggestions? I don't have any unusual secondary languages installed, and am on OSX.

**Comment by Jayanth-Kulkarni** [comment]
I had a similar issue .. had forgotten to add end document tag it works fine now

**Comment by msiniscalchi** [comment]
Please close if the issue is resolved.
