### ISSUE TITLE
Latest release just presented this as an error

### ISSUE THREAD

**Issue by poulter7** [SublimeText/LaTeXTools#581]
I'm using SublimeText 3083 on a Mac, invoking a standard build and I see this error, any ideas?

    Traceback (most recent call last):
      File "./threading.py", line 901, in _bootstrap_inner
      File "/Development/latexing/progress.py", line 16, in run
      File "/Development/latexing/compiler.py", line 66, in <lambda>
      File "/Development/latexing/compiler.py", line 71, in on_run
      File "/Development/latexing/terminal.py", line 236, in find_executable
      File "/Development/latexing/terminal.py", line 255, in command_executable
      File "/Development/latexing/terminal.py", line 338, in set_envionpath
      File "/Development/latexing/tools.py", line 430, in load_resource
      File "./json/__init__.py", line 319, in loads
      File "./json/decoder.py", line 352, in decode
      File "./json/decoder.py", line 370, in raw_decode
    ValueError: No JSON object could be decoded

**Comment by msiniscalchi** [comment]
Wrong plugin. Check your error message: it says "latexing".

Please close (and start using LaTeXTools...)
