### ISSUE TITLE
After automatic update build fails

### ISSUE THREAD

**Issue by pmico** [SublimeText/LaTeXTools#594]
Editing: 
OK I find solution just in #589 issue.
```
In line 133 change the indendation from spaces to tabs
```
All work now.

-------------------
Hi 
I suppose it has been an automatic update since i saw a new sheet with bugs update etc ...
Then I tried to compile a tex file with command-b (osx 10.11, sublime text 2) and i got a blank output in build results.
I opened console and I found this error:
```
Writing file ...tex with encoding UTF-8
Traceback (most recent call last):
  File "./sublime_plugin.py", line 337, in run_
  File "./makePDF.py", line 337, in run
  File ".../LaTeXTools/builders/traditionalBuilder.py", line 133
    cmd[i] = c.replace("%E", engine)
    ^
IndentationError: expected an indented block
```
Of course, I did nothing with this file and if I open it, indentation is present as you can see here:
```python
			if engine != self.engine:
				self.display("Engine: " + self.engine + " -> " + engine + ". ")

			for i, c in enumerate(cmd):
                cmd[i] = c.replace("%E", engine)

		# handle any options
		if texify or latexmk:
```
I know nothing about python, so, I don't understand why this happens.
Thanks for any information.

**Comment by pmico** [comment]
I find solution just in #589 issue.
```
In line 133 change the indendation from spaces to tabs
```
All work now.

Issue closed.

**Comment by floswald** [comment]
same here. mac os 10.10.5. it worked a couple of hours ago.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "/Users/florian.oswald/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 337, in run
    builder_module = __import__(builder_name + 'Builder')
  File "/Users/florian.oswald/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/traditionalBuilder.py", line 133
    cmd[i] = c.replace("%E", engine)
                                   ^
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "/Users/florian.oswald/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 337, in run
    builder_module = __import__(builder_name + 'Builder')
  File "/Users/florian.oswald/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/traditionalBuilder.py", line 133
    cmd[i] = c.replace("%E", engine)
                                   ^
TabError: inconsistent use of tabs and spaces in indentation
```

used the fix above.

**Comment by pmico** [comment]
Thanks!!! I discovered your issue, just after i published mine and i use your solution.
Thanks again



En 23 nov 2015 14:18, en 14:18, Florian Oswald <notifications@github.com> escrito:
