### ISSUE TITLE
\cite dropdown no longer working in new release of LaTeXTools (3.7.3)

### ISSUE THREAD

**Issue by qnp** [SublimeText/LaTeXTools#694]
Hello,

Since the released version 3.7.3 (2016-04-20), the bibliography parsing and the dropdown menu when typing `\cite{` command does no longer work. 
This release was intended to fix additional issues with bib parsing reported on #686, and implements three new features about bibliography parsing:
  - Improved bibiography parsing; should handle UTF-8 and most formatting
  - Support for most citation commands and support for the various ways BibLaTeX has to add bibliographies
  - Plugin system for handling viewers, builders, and bibliography file parsing

My project is consituted of a `main.tex` where I declare `\bibliography{biblio}` and several other tex files that are included in `main.tex`. To have bibliography parsing available in the other tex files, I used `\iffalse \bibliography{../biblio.bib} \fi`. This was working very well.

Now, when I write `\cite{` in the other tex files, **nothing** is happening. Moreover, when I white `\cite{` in `main.tex`, I have the following error:
`An error occurred while trying to run kpsewhich. TEXMF tree could not be accessed.`

Do you know how to overcome this issue, or permanently fix it ?

Best regards

**Comment by qnp** [comment]
It appears to be the bibliography file which is not parsed correctly. I had an error because keys entries begining by `_` where not allowed (they were before, and automatically generated keys, from Zotero for example, may begin with `_`).

Now I have an other error (in both cases, typing `\cite{` from `main.tex` or the other tex files). But the line in my bib file which causes the error is not specified... (hard to debugg):
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./latex_cite_completions.py", line 743, in run
  File "./latex_cite_completions.py", line 656, in get_cite_completions
  File "./latex_cite_completions.py", line 414, in run_plugin_command
  File "./latex_cite_completions.py", line 375, in _run_command
  File "./bibliography_plugins/traditionalBibliography.py", line 130, in get_entries
  File "./bibliography_plugins/bibtex/parser.py", line 86, in parse
  File "./bibliography_plugins/bibtex/parser.py", line 191, in entry
  File "./bibliography_plugins/bibtex/parser.py", line 215, in entry_key
  File "./bibliography_plugins/bibtex/parser.py", line 338, in unexpected_token
SyntaxError: unexpected number; expecting identifier
```

**Comment by PieterO** [comment]
I'm having the same issue, I have tried simple files without _ in cite keys as suggested.
It still builds my files but nothing happens with auto-completion.
Is there anyway to easily revert to an older edition of latextools? 
Kind regards.

**Comment by ig0774** [comment]
@PieterO: Easy way to revert is to download [v3.6.3](https://github.com/SublimeText/LaTeXTools/archive/v3.6.3.zip) and replace your LaTeXTools package with that. You may lose PackageControl auto-updating if you do so, however.

**Comment by ig0774** [comment]
@PieterO: If you can find out what the error is from the console, I'm trying to address these issues quickly.

**Comment by vor77** [comment]
Same thing, no bibitems starting with "_", and no big help from the console :(
Unfortunately the difference with working and non-working bibtex file is about 500 entries.

`Loaded 0 bibitems
Found 0 total bib entries
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\latex_cite_completions.py", line 743, in run
  File ".\latex_cite_completions.py", line 656, in get_cite_completions
  File ".\latex_cite_completions.py", line 414, in run_plugin_command
  File ".\latex_cite_completions.py", line 375, in _run_command
  File ".\bibliography_plugins\traditionalBibliography.py", line 130, in get_entries
  File ".\bibliography_plugins\bibtex\parser.py", line 86, in parse
  File ".\bibliography_plugins\bibtex\parser.py", line 191, in entry
  File ".\bibliography_plugins\bibtex\parser.py", line 215, in entry_key
  File ".\bibliography_plugins\bibtex\parser.py", line 333, in unexpected_token
SyntaxError: 2:13 - unexpected number; expecting identifier`

**Comment by vor77** [comment]
My problem was citekeys starting with "3GPP..." so easy guess that numbers are not ok. Although for some reason generating the popup list is now very slow. The size of list can't be the reason as it was working nice just last week.

**Comment by ig0774** [comment]
@qnp: You're absolute right. Both numbers and leading `_` should be supported. For some reason, I was under the impression that they didn't work. v3.7.4 now supports these.

**Comment by ig0774** [comment]
@vor77: Hopefully the slowness should be a one-time thing (assuming your bibliography doesn't change much).

**Comment by qnp** [comment]
@ig0774 great thanks, with this new version all is working again. You saved my PhD, haha ;)

**Comment by PieterO** [comment]
@ig0774 Sorry for not replying quickly. It now works thank you very much. 
The loading of a larger bib file takes about 8 seconds every time I use \cite{, something is still going slightly amiss. Not a fatal error however.

```
['/home/pieter/library.bib']
Loaded 712 bibitems
Found 712 total bib entries
latex_cite_completion called with index -1
```
