### ISSUE TITLE
autotrigger broken since new update

### ISSUE THREAD

**Issue by tobiasgerstenberg** [SublimeText/LaTeXTools#695]
autotrigger for \cite or \ref is not working for me anymore since the newest update today. when pressing "C-l, x" the following error message pops up: Ref/cite: unrecognized format.

and this is shown in the console: 

201598
True True
error: Ref/cite: unrecognized format.

**Comment by tobiasgerstenberg** [comment]
upon trying \cite{ i get the following in the console

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./latex_cite_completions.py", line 743, in run
  File "./latex_cite_completions.py", line 656, in get_cite_completions
  File "./latex_cite_completions.py", line 414, in run_plugin_command
  File "./latex_cite_completions.py", line 375, in _run_command
  File "./bibliography_plugins/traditionalBibliography.py", line 131, in get_entries
  File "./bibliography_plugins/bibtex/parser.py", line 57, in parse
  File "./bibliography_plugins/bibtex/lexer.py", line 88, in tokenize
  File "./bibliography_plugins/bibtex/lexer.py", line 289, in token_error
SyntaxError: 423:2 - unrecognised token "__Markedentry = {[PaLS:6]},"

**Comment by ig0774** [comment]
Thanks for the report. This was already addressed in a (very) recent update. You should be able to get it working by updating LaTeXTools (from the command palette, select `Package Control: Upgrade Package`).

**Comment by tobiasgerstenberg** [comment]
thanks, upgrade + restarting sublime fixed it.
