### ISSUE TITLE
v3.7.7 \cite toggle gone...

### ISSUE THREAD

**Issue by jvrsgsty** [SublimeText/LaTeXTools#702]
I am having a similar problem as the one posted in Issue #254 ...
The `\cite` command would open a drop down list with all my references in them so I could insert one quickly. It just stopped working after a recent LaTeXTools update. I am working with Sublime Text 2.0.2 Build 2221, LaTeXTools version 3.7.7 and Mac OS X 10.10.5. 

A minimal working example of my latex document: 
```latex
\documentclass[12pt]{report}
\usepackage[utf8]{inputenc}
\title{a title}
\author{an author}
\begin{document}
  \maketitle
  \pagenumbering{arabic}
  \setcounter{page}{1}
  \include{chapters/ch1}
  \include{chapters/ch2}
  \clearpage
  \bibliography{references}
  \bibliographystyle{IEEEtran}
  \nocite{*}
\end{document}
```

Whenever I type `\cite{` in either the main tex file or `chapters/ch*.tex` the toggle is not displayed on screen when it previously was. I obviously reference my root file from the chapters using the `%!TEX root = ../main.tex` annotation on the chapter files. Plus, my `references.bib` file is located in my root directory, along with the `main.tex` file. What puzzles me is that it worked perfectly before and after the update, autocomplete functionality is gone. 

**ST2 console output: **
```
255
True True
Dispatching cite
256
TEX root: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/tesis.tex'
Searching file: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/tesis.tex'
Searching file: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/capitulos/introduccion.tex'
Searching file: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/capitulos/estilometria.tex'
Searching file: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/capitulos/fundamentos.tex'
Searching file: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/capitulos/diseno.tex'
Searching file: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/capitulos/experimentos.tex'
Searching file: u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/capitulos/conclusiones.tex'
Bib files found: 
[u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/referencias.bib']
Files:
[u'/Users/jvrsgsty/Documents/ITAM/Tesis/Documento/referencias.bib']
Could not find bibliography plugin named t. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named r. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named a. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named d. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named t. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named o. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named n. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named a. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named l. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named _. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named b. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named b. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named l. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named o. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named g. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named r. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named a. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named p. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named h. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Could not find bibliography plugin named y. Please ensure your LaTeXTools.sublime-settings is configured correctly.
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./latex_cite_completions.py", line 743, in run
  File "./latex_cite_completions.py", line 656, in get_cite_completions
  File "./latex_cite_completions.py", line 421, in run_plugin_command
latex_cite_completions.BibPluginError: Could not find a plugin to handle 'get_entries'. See the console for more details
```

**Comment by ig0774** [comment]
This was fixed in v3.7.8.
