### ISSUE TITLE
new_bibliography and cryptobib: does not work

### ISSUE THREAD

**Issue by tlepoint** [SublimeText/LaTeXTools#757]
Hi,

The `"bibliography": "new_bibliography"` setting doesn't work at all with [cryptobib](https://github.com/cryptobib/export), which is a widely used (and large!) bib file used in cryptography. Would it be possible to know whether this is a bug due to the parser or a wrong formatting in the bib file?

Thanks!

**Comment by ig0774** [comment]
Thanks for the issue report. I've tracked down the issue (it had to do with the `EPRINT:Castelluccia06` entry which had a title that ended with `\\"`). I'll have a fix in the next release (which should be soon).

**Comment by tlepoint** [comment]
Thanks for looking into it. I updated LaTeXTools with the HEAD version locally, changed the "bibliography" setting to "new" in my sublime-project file, and restarted everything. It takes long, but the cite panel does not show up, so it doesn't seem to work here. Does it show up for you?

(Weird title btw ;)).

**Comment by r-stein** [comment]
Open the ST console ``ctrl+` `` for more information.

Aside: The result will be cached after the first run of cite. Hence additional runs won't take as long.

**Comment by tlepoint** [comment]
Here is what I get with `\bibliography{cryptobib/abbrev3,cryptobib/crypto}`:

```
1464
True True
Dispatching cite
1465
TEX root: '/[HIDDEN]/tex/qlass.tex'
Searching file: '/[HIDDEN]/tex/qlass.tex'
Searching file: '/[HIDDEN]/tex/summary.tex'
Searching file: '/[HIDDEN]/tex/project.tex'
Bib files found: 
['/[HIDDEN]/tex/cryptobib/crypto.bib', '/[HIDDEN]/tex/cryptobib/abbrev3.bib']
Files:
['/[HIDDEN]/tex/cryptobib/crypto.bib', '/[HIDDEN]/tex/cryptobib/abbrev3.bib']
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 705, in run
    completions, prefix, post_brace, new_point_a, new_point_b = get_cite_completions(view, point)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 619, in get_cite_completions
    completions = run_plugin_command('get_entries', *bib_files)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 369, in run_plugin_command
    result = _run_command(plugins)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latex_cite_completions.py", line 332, in _run_command
    result = getattr(plugin, command)(*args, **kwargs)
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/bibliography_plugins/newBibliography.py", line 136, in get_entries
    bib_data = parser.parse(bibf.read())
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/external/bibtex/parser.py", line 80, in parse
    string = self.string()
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/external/bibtex/parser.py", line 168, in string
    node.value = self.string_value()
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/external/bibtex/parser.py", line 229, in string_value
    self.unexpected_token('quoted_string or value')
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/external/bibtex/parser.py", line 333, in unexpected_token
    expecting
SyntaxError: 127:671 - unexpected identifier; expecting quoted_string or value
```

**Comment by ig0774** [comment]
I only looked into crypto.bib, not the abbreviation files. I'm going to back out the change and play around with things some more.

**Comment by ig0774** [comment]
Ok... If you're willing to test things out, see #759 or pull from [this branch](https://github.com/ig0774/LaTeXTools/tree/fix_757). (It's much better to see if these work in actual documents then in the dummy documents I dream up).

**Comment by ig0774** [comment]
I've pulled #759 into the main release because I regard it as a bugfix for the bib-file parsing. We'll hopefully get the caching improvements discussed there merged in soon.
