### ISSUE TITLE
texlive 2016 and project builds

### ISSUE THREAD

**Issue by musmo** [SublimeText/LaTeXTools#765]
So I got a sublime project that looks like this
```
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings" : {
        "TEXroot": "main.tex",
        // "builder_settings": {
            // "program": "xelatex",
        // }
    }
}
```
which worked perfectly with texlive 2015. 
```
	"windows": {
		"texpath" : "C:\\texlive\\2015\\bin\\win32;$PATH",
		// TeX distro: "miktex" or "texlive"
		"distro" : "texlive",
	}
```
I just installed texlive 2016. Switching above to `"texpath" : "C:\\texlive\\2016\\bin\\win32;$PATH",
`, breaks my project build. The error is that it cannot find the file `main.tex`

**Comment by ig0774** [comment]
Where is `main.tex` relative to your `sublime-project` file?

**Comment by musmo** [comment]
Same folder

**Comment by ig0774** [comment]
Strange... Can you show the generated command? It should be in the Sublime Text console (**View | Console**).

**Comment by musmo** [comment]
```
DPI scale: 1
startup, version: 3114 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Mus/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Mus/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Mus/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["BracketFlasher", "BracketHighlighter", "Markdown"]
pre session restore time: 0.542665
startup time: 0.671665
first paint time: 0.672665
first paint time: 0.673665
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin AlignTab.aligner
reloading plugin AlignTab.aligntab
reloading plugin AlignTab.hist
reloading plugin AlignTab.parser
reloading plugin AlignTab.table
reloading plugin AlignTab.wclen
reloading plugin BeautifyLatex.beautify_latex
reloading plugin BracketGuard.BracketGuard
reloading plugin Dictionaries.Dictionaries
reloading plugin Diffy.diffy
reloading plugin FileDiffs.file_diffs
reloading plugin Fortran.InlineDocsHover
reloading plugin Fortran.InlineLatexHover
reloading plugin Fortran.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "linter in C:\Users\Mus\AppData\Roaming\Sublime Text 3\Installed Packages\Fortran.sublime-package", line 9, in <module>
ImportError: No module named 'SublimeLinter'
reloading plugin Indent XML.indentxml
reloading plugin MatlabFilenameAutoComplete.MatlabAutoComplete
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pandoc.Pandoc
reloading plugin Whitespace.Whitespace
reloading plugin WordCount.WordCount
reloading plugin Wrap Plus.wrap_plus
reloading plugin LaTeXTools.00_add_external_libs_to_path
reloading plugin LaTeXTools.01_reload_submodules
reloading plugin LaTeXTools.02_temp_file_cleanup
reloading plugin LaTeXTools.biblatex_crossref_completions
reloading plugin LaTeXTools.biblatex_field_name_completions
reloading plugin LaTeXTools.biblatex_name_completions
reloading plugin LaTeXTools.biblatex_snippet_completions
reloading plugin LaTeXTools.biblatex_syntax_listener
reloading plugin LaTeXTools.change_environment
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.detect_spellcheck
reloading plugin LaTeXTools.getRegion
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpto_tex_file
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_cwl_completions
reloading plugin LaTeXTools.latex_env_completions
reloading plugin LaTeXTools.latex_input_completions
reloading plugin LaTeXTools.latex_installed_packages
reloading plugin LaTeXTools.latex_ref_cite_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexDocumentationViewer
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.latexFillAll
reloading plugin LaTeXTools.latextools_default_settings
reloading plugin LaTeXTools.latextools_plugin
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.texSyntaxListener
reloading plugin LaTeXTools.toggle_auto
reloading plugin LaTeXTools.toggle_focus
reloading plugin LaTeXTools.toggle_fwdsync
reloading plugin LaTeXTools.toggle_show
plugins loaded
Loading LaTeXTools plugins...
Loaded LaTeXTools plugins ['traditional_bibliography', 'new_bibliography'] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins
Loaded LaTeXTools plugins ['base_viewer'] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\viewers\base_viewer.py
Loaded LaTeXTools plugins ['preview_viewer', 'zathura_viewer', 'skim_viewer', 'evince_viewer', 'okular_viewer', 'command_viewer', 'sumatra_viewer'] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\viewers
Loaded LaTeXTools plugins [] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\User
Loaded LaTeXTools plugins [] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\User
Loaded LaTeXTools plugins ['pdf_builder'] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\builders\pdfBuilder.py
Loaded LaTeXTools plugins ['traditional_builder', 'script_builder', 'simple_builder', 'basic_builder'] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\builders
Loaded LaTeXTools plugins [] from path C:\Users\Mus\AppData\Roaming\Sublime Text 3\Packages\User
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
4
Welcome to thread Thread-4
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', '--output-directory=C:\\Users\\Mus\\book\\f8a5e561e86b1bec708aa216a6a88c02', '--jobname=lbm-book', 'main.tex']
Package Control: Skipping automatic upgrade, last run at 2016-07-08 17:06:16, next run at 2016-07-08 18:06:16 or after
Finished normally
12
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
3
Welcome to thread Thread-7
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', '--output-directory=C:\\Users\\Mus\\book\\f8a5e561e86b1bec708aa216a6a88c02', '--jobname=lbm-book', 'main.tex']
Finished normally
0
indexing [queue 2]: no files were indexed out of the 3 queued, abandoning crawl
indexing [queue 3]: no files were indexed out of the 4 queued, abandoning crawl
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
3
Welcome to thread Thread-9
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', '--output-directory=C:\\Users\\Mus\\book\\f8a5e561e86b1bec708aa216a6a88c02', '--jobname=lbm-book', 'main.tex']
Finished normally
12
indexing [queue 6]: no files were indexed out of the 3 queued, abandoning crawl
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/LaTeXTools.sublime-settings
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
3
Welcome to thread Thread-16
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', '--output-directory=C:\\Users\\Mus\\book\\f8a5e561e86b1bec708aa216a6a88c02', '--jobname=lbm-book', 'main.tex']
indexing [queue 9]: no files were indexed out of the 9 queued, abandoning crawl
indexing [queue 10]: no files were indexed out of the 11 queued, abandoning crawl
indexing [queue 11]: no files were indexed out of the 10 queued, abandoning crawl
indexing [queue 12]: no files were indexed out of the 11 queued, abandoning crawl
Finished normally
12
False True True
Jump to:  33 0
<class '_latextools_sumatra_viewer.SumatraViewer'>
reloading settings Packages/User/LaTeXTools.sublime-settings
error: Please save your file before attempting to build.
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
3
Welcome to thread Thread-22
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', '--output-directory=C:\\Users\\Mus\\book\\f8a5e561e86b1bec708aa216a6a88c02', '--jobname=lbm-book', 'main.tex']
Finished normally
12
```

**Comment by ig0774** [comment]
Could you try removing the `"TEXroot"` setting from your project file and building from `main.tex`?

**Comment by musmo** [comment]
Yes I removed TEXroot and jobname and tried building directly from main.tex using 2015 and 2016. 2016 still errors with
```[Compiling C:\Users\Mus\book\main.tex]

TraditionalBuilder: Engine: pdflatex. Invoking latexmk... done.

Could not find log file main.log!
Output from compilation:

Latexmk: This is Latexmk, John Collins, 22 April 2016, version: 4.45.
Latexmk: Changing directory to './'
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -interaction=nonstopmode -synctex=1 -recorder -output-directory="C:\Users\Mus\book\f8a5e561e86b1bec708aa216a6a88c02"  "main.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/W32TeX) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `main.tex'.
<*> main.tex
            
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<*> main.tex
            
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on "C:\Users\Mus\book\f8a5e561e86b1bec708aa216a6a88c02/texput.log".
Failure to make 'C:\Users\Mus\\book\f8a5e561e86b1bec708aa216a6a88c02/main.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: (Pdf)LaTeX failed to generate the expected log file 'C:\Users\Mus\book\f8a5e561e86b1bec708aa216a6a88c02/main.log'
Latexmk: Did not finish processing file 'main.tex':
   (Pdf)LaTeX failed to generate the expected log file 'C:\Users\Mus\book\f8a5e561e86b1bec708aa216a6a88c02/main.log'
Latexmk: Undoing directory change
Latexmk: Errors, in force_mode: so I tried finishing targets
C:\texlive\2016\bin\win32\runscript.tlu:679: command failed with exit code 12:
perl.exe c:\texlive\2016\texmf-dist\scripts\latexmk\latexmk.pl -cd -f -pdf -interaction=nonstopmode -synctex=1 "--output-directory=C:\Users\Mus\book\f8a5e561e86b1bec708aa216a6a88c02" main.tex
```
Note I am able to build other files using 2016, it's only a problem with this project based file

**Comment by ig0774** [comment]
This seems like a very strange issue and I only have rather bizarre theories for what can be causing it. Can you try moving the `tex` file and corresponding `sublime-project` (as well as any other source files) to a new folder, opening the project in ST and compiling?

**Comment by musmo** [comment]
I tried and it didn't work again. Basically something is getting mangled when passed to latexmk with project files and such with sublime's cache of the directories of where these exist. Specifically when you set an output directory it doesn't properly parse the backslash on windows. This is my suspicion.

**Comment by ig0774** [comment]
The comment should be:

```latex
%!TEX output_directory = <<project>>
```

The quotes aren't parsed in this context; they're just passed straight through, which results in all kinds of issues, in particular, the one you're seeing there.

**Comment by musmo** [comment]
Ah of course, fixing that small issue.  I noticed something interesting basically in the output directory  texputs.fls and texput.log do not get properly renamed.

**Comment by ig0774** [comment]
No, I can't. Everything works as I'd expect on my Windows machine with TeXLive 2016.

**Comment by musmo** [comment]
ahhhhh. I figured it out. Basically I already had 2015 in my path and I had
`		"texpath" : "C:\\texlive\\2016\\bin\\win32:$PATH"`, which confuses everything. I had to delete the `$PATH` variable and instead use `		"texpath" : "C:\\texlive\\2016\\bin\\win32",`

Now everything works. Sorry for that. Thanks and I look forward to all the updates you have been adding.
