### ISSUE TITLE
'ViewPdf' object has no attribute 'view'

### ISSUE THREAD

**Issue by gncs** [SublimeText/LaTeXTools#844]
When I select "LaTeXTools: View PDF" with LaTeXTools (v3.11.0) and Sublime Text 3 (build 3124) I get the following error message:
```
Traceback (most recent call last):
  File "/home/gncs/local/sublime_text_3/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/home/gncs/.config/sublime-text-3/Packages/LaTeXTools/jumpToPDF.py", line 237, in run
    root = getTeXRoot.get_tex_root(self.view)
AttributeError: 'ViewPdf' object has no attribute 'view'
```
Is this a bug? Thanks :)

**Comment by r-stein** [comment]
Thanks for reporting this, it should be fixed in `3.11.1`
