### ISSUE TITLE
Ubuntu GNOME3 PDF sync

### ISSUE THREAD

**Issue by skulumani** [SublimeText/LaTeXTools#931]
I'm having an issue with jumping between the PDF and source. Here's an output from the console

~~~
Welcome to thread Thread-52
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', 'proposal.tex']
Running "latexmk -cd -f -pdf -interaction=nonstopmode -synctex=1 proposal.tex"
Finished normally
0
False True True
Jump to:  10 42
<class '_latextools_evince_viewer.EvinceViewer'>
Running "ps xv"
Running "/home/shankar/anaconda3/bin /home/shankar/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_forward_search /home/shankar/Documents/dissertation_proposal/proposal.pdf 11 /home/shankar/Documents/dissertation_proposal/tex/introduction.tex"
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/home/shankar/.config/sublime-text-3/Packages/LaTeXTools/jumpToPDF.py", line 159, in run
    viewer.forward_sync(pdffile, srcfile, line, col, keep_focus=keep_focus)
  File "/home/shankar/.config/sublime-text-3/Packages/LaTeXTools/viewers/evince_viewer.py", line 116, in forward_sync
    use_texpath=False
  File "/home/shankar/.config/sublime-text-3/Packages/LaTeXTools/latextools_utils/external_command.py", line 208, in external_command
    cwd=cwd
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
~~~

It will fail when compiling or trying to use the hotkeys to jump to PDF. I have tested that the command 

~~~
/bin/sh evince_sync python3 subl /home/shankar/Documents/dissertation_proposal/proposal.pdf
~~~

Does work because it'll open and jump to the PDF. I am using Anaconda but have set the correct path and it's verified in the new LatexTools check system command.

Any advice or suggestions would be appreciated.

**Comment by ig0774** [comment]
It looks like your `python` or `python2` setting is misconfigured. It should point to the actual Python executable, i.e., `/home/shankar/anaconda3/bin/python`, rather than the folder containing the executable.

Incidentally, if you're going to use Anaconda here (and I wouldn't recommend it), you need to be sure you have the `dbus` and `gobject` modules installed.

**Comment by skulumani** [comment]
Thank you for your comments. The path issues make sense now.

I appreciate the help
