### ISSUE TITLE
Couple exceptions while browsing through Goto Anything

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/LaTeXTools#980]
The tracebacks should speak for themselves. The first one is based on an incorrect assumption and the second is due to the API being inconsistend ocassionally when opening/creating a view (upstream issue exists).

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 435, in on_load_async
    callback.on_load_async(v)
  File "C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_cwl_completions.py", line 329, in on_load_async
    point = view.sel()[0].end()
  File "C:\Program Files\Sublime Text 3\sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
Traceback (most recent call last):
  File "C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 601, in update_phantoms
    self._update_phantoms()
  File "C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 615, in _update_phantoms
    for g in range(view.window().num_groups())):
AttributeError: 'NoneType' object has no attribute 'num_groups'
```

**Comment by ig0774** [comment]
Thanks for the bug report!
